name: deploy
on:
  push:
    branches:
      - main
    paths:
      - 'shutup.css'
  workflow_dispatch:
jobs:
  prepare-and-deploy-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v2
      - name: Prepare stylesheet
        run: |
          mkdir -p $GITHUB_WORKSPACE/build
          cp $GITHUB_WORKSPACE/shutup.css $GITHUB_WORKSPACE/build/
          brotli -9 --no-copy-stat --stdout $GITHUB_WORKSPACE/build/shutup.css > $GITHUB_WORKSPACE/build/shutup.css.br
          gzip --best --no-name --stdout $GITHUB_WORKSPACE/build/shutup.css > $GITHUB_WORKSPACE/build/shutup.css.gz
      - name: Deploy update
        uses: AEnterprise/rsync-deploy@06168fb7cc757886bb6e8d143caf20935987beb3
        env:
          DEPLOY_KEY: ${{ secrets.SERVER_SSH_KEY }}
          ARGS: "-havP --progress"
          SERVER_PORT: ${{ secrets.SERVER_PORT }}
          FOLDER: "build/"
          SERVER_IP: ${{ secrets.SERVER_IP }}
          USERNAME: ${{ secrets.USERNAME }}
          SERVER_DESTINATION: ${{ secrets.SERVER_DESTINATION }}
  webextension-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v2
          with:
            path: shutup-css
      - name: Checkout webextension
        uses: actions/checkout@v2
          with:
            token: ${{ secrets.PR_TOKEN }}
            repository: RickyRomero/shut-up-webextension
            path: shut-up-webextension
      - name: Copy CSS
        run: |
          cp shutup-css/shutup.css shut-up-webextension/resources/shutup.css
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@d9d6fd980e1e0904e8e4dce3f0992640091bde37
          with:
            token: ${{ secrets.PR_TOKEN }}
            path: shut-up-webextension
            commit-message: Update shutup.css
            title: Update shutup.css
            body:
            assignees: RickyRomero
            branch: stylesheet-automation
            delete-branch: true
